// Generated by `npm run images` (scripts/guide-images.js) from assets/guides/. Don't edit by hand.
// Metro only bundles static require() paths, so every picture is listed here. Only complete guides are in it.
import type { GuideId, GuideImages } from './guides';

export const GUIDE_IMAGES = {
  man: {
    hero: {
      home: require('@/assets/guides/man/hero/home.webp'),
      paywall: require('@/assets/guides/man/hero/paywall.webp'),
    },
    exercises: {
      '01-jaw-clench': {
        relaxed: require('@/assets/guides/man/exercises/01-jaw-clench/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/01-jaw-clench/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/01-jaw-clench/thumb.webp'),
      },
      '02-chin-lift': {
        relaxed: require('@/assets/guides/man/exercises/02-chin-lift/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/02-chin-lift/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/02-chin-lift/thumb.webp'),
      },
      '03-jaw-jut': {
        relaxed: require('@/assets/guides/man/exercises/03-jaw-jut/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/03-jaw-jut/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/03-jaw-jut/thumb.webp'),
      },
      '04-mewing': {
        relaxed: require('@/assets/guides/man/exercises/04-mewing/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/04-mewing/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/04-mewing/thumb.webp'),
      },
      '12-tongue-press': {
        relaxed: require('@/assets/guides/man/exercises/12-tongue-press/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/12-tongue-press/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/12-tongue-press/thumb.webp'),
      },
      '11-chin-tuck': {
        relaxed: require('@/assets/guides/man/exercises/11-chin-tuck/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/11-chin-tuck/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/11-chin-tuck/thumb.webp'),
      },
      '05-neck-stretch': {
        relaxed: require('@/assets/guides/man/exercises/05-neck-stretch/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/05-neck-stretch/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/05-neck-stretch/thumb.webp'),
      },
      '06-cheek-lift': {
        relaxed: require('@/assets/guides/man/exercises/06-cheek-lift/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/06-cheek-lift/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/06-cheek-lift/thumb.webp'),
      },
      '07-fish-face': {
        relaxed: require('@/assets/guides/man/exercises/07-fish-face/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/07-fish-face/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/07-fish-face/thumb.webp'),
      },
      '13-smiling-fish': {
        relaxed: require('@/assets/guides/man/exercises/13-smiling-fish/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/13-smiling-fish/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/13-smiling-fish/thumb.webp'),
      },
      '08-cheek-puff': {
        relaxed: require('@/assets/guides/man/exercises/08-cheek-puff/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/08-cheek-puff/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/08-cheek-puff/thumb.webp'),
      },
      '14-o-stretch': {
        relaxed: require('@/assets/guides/man/exercises/14-o-stretch/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/14-o-stretch/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/14-o-stretch/thumb.webp'),
      },
      '15-lion-face': {
        relaxed: require('@/assets/guides/man/exercises/15-lion-face/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/15-lion-face/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/15-lion-face/thumb.webp'),
      },
      '18-lip-press': {
        relaxed: require('@/assets/guides/man/exercises/18-lip-press/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/18-lip-press/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/18-lip-press/thumb.webp'),
      },
      '19-pout': {
        relaxed: require('@/assets/guides/man/exercises/19-pout/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/19-pout/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/19-pout/thumb.webp'),
      },
      '20-lip-corner-lift': {
        relaxed: require('@/assets/guides/man/exercises/20-lip-corner-lift/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/20-lip-corner-lift/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/20-lip-corner-lift/thumb.webp'),
      },
      '21-smile-line-press': {
        relaxed: require('@/assets/guides/man/exercises/21-smile-line-press/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/21-smile-line-press/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/21-smile-line-press/thumb.webp'),
      },
      '09-brow-lift': {
        relaxed: require('@/assets/guides/man/exercises/09-brow-lift/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/09-brow-lift/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/09-brow-lift/thumb.webp'),
      },
      '22-forehead-press': {
        relaxed: require('@/assets/guides/man/exercises/22-forehead-press/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/22-forehead-press/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/22-forehead-press/thumb.webp'),
      },
      '16-wide-eyes': {
        relaxed: require('@/assets/guides/man/exercises/16-wide-eyes/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/16-wide-eyes/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/16-wide-eyes/thumb.webp'),
      },
      '17-lower-lid-lift': {
        relaxed: require('@/assets/guides/man/exercises/17-lower-lid-lift/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/17-lower-lid-lift/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/17-lower-lid-lift/thumb.webp'),
      },
      '23-v-eyes': {
        relaxed: require('@/assets/guides/man/exercises/23-v-eyes/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/23-v-eyes/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/23-v-eyes/thumb.webp'),
      },
      '10-eye-squeeze': {
        relaxed: require('@/assets/guides/man/exercises/10-eye-squeeze/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/10-eye-squeeze/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/10-eye-squeeze/thumb.webp'),
      },
      '24-jaw-release': {
        relaxed: require('@/assets/guides/man/exercises/24-jaw-release/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/24-jaw-release/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/24-jaw-release/thumb.webp'),
      },
      '25-jawline-sweep': {
        relaxed: require('@/assets/guides/man/exercises/25-jawline-sweep/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/25-jawline-sweep/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/25-jawline-sweep/thumb.webp'),
      },
      '26-frown-release': {
        relaxed: require('@/assets/guides/man/exercises/26-frown-release/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/26-frown-release/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/26-frown-release/thumb.webp'),
      },
      '27-temple-circles': {
        relaxed: require('@/assets/guides/man/exercises/27-temple-circles/relaxed.webp'),
        exercise: require('@/assets/guides/man/exercises/27-temple-circles/exercise.webp'),
        thumb: require('@/assets/guides/man/exercises/27-temple-circles/thumb.webp'),
      },
    },
  },
  woman: {
    hero: {
      home: require('@/assets/guides/woman/hero/home.webp'),
      paywall: require('@/assets/guides/woman/hero/paywall.webp'),
    },
    exercises: {
      '01-jaw-clench': {
        relaxed: require('@/assets/guides/woman/exercises/01-jaw-clench/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/01-jaw-clench/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/01-jaw-clench/thumb.webp'),
      },
      '02-chin-lift': {
        relaxed: require('@/assets/guides/woman/exercises/02-chin-lift/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/02-chin-lift/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/02-chin-lift/thumb.webp'),
      },
      '03-jaw-jut': {
        relaxed: require('@/assets/guides/woman/exercises/03-jaw-jut/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/03-jaw-jut/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/03-jaw-jut/thumb.webp'),
      },
      '04-mewing': {
        relaxed: require('@/assets/guides/woman/exercises/04-mewing/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/04-mewing/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/04-mewing/thumb.webp'),
      },
      '12-tongue-press': {
        relaxed: require('@/assets/guides/woman/exercises/12-tongue-press/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/12-tongue-press/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/12-tongue-press/thumb.webp'),
      },
      '11-chin-tuck': {
        relaxed: require('@/assets/guides/woman/exercises/11-chin-tuck/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/11-chin-tuck/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/11-chin-tuck/thumb.webp'),
      },
      '05-neck-stretch': {
        relaxed: require('@/assets/guides/woman/exercises/05-neck-stretch/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/05-neck-stretch/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/05-neck-stretch/thumb.webp'),
      },
      '06-cheek-lift': {
        relaxed: require('@/assets/guides/woman/exercises/06-cheek-lift/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/06-cheek-lift/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/06-cheek-lift/thumb.webp'),
      },
      '07-fish-face': {
        relaxed: require('@/assets/guides/woman/exercises/07-fish-face/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/07-fish-face/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/07-fish-face/thumb.webp'),
      },
      '13-smiling-fish': {
        relaxed: require('@/assets/guides/woman/exercises/13-smiling-fish/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/13-smiling-fish/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/13-smiling-fish/thumb.webp'),
      },
      '08-cheek-puff': {
        relaxed: require('@/assets/guides/woman/exercises/08-cheek-puff/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/08-cheek-puff/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/08-cheek-puff/thumb.webp'),
      },
      '14-o-stretch': {
        relaxed: require('@/assets/guides/woman/exercises/14-o-stretch/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/14-o-stretch/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/14-o-stretch/thumb.webp'),
      },
      '15-lion-face': {
        relaxed: require('@/assets/guides/woman/exercises/15-lion-face/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/15-lion-face/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/15-lion-face/thumb.webp'),
      },
      '18-lip-press': {
        relaxed: require('@/assets/guides/woman/exercises/18-lip-press/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/18-lip-press/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/18-lip-press/thumb.webp'),
      },
      '19-pout': {
        relaxed: require('@/assets/guides/woman/exercises/19-pout/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/19-pout/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/19-pout/thumb.webp'),
      },
      '20-lip-corner-lift': {
        relaxed: require('@/assets/guides/woman/exercises/20-lip-corner-lift/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/20-lip-corner-lift/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/20-lip-corner-lift/thumb.webp'),
      },
      '21-smile-line-press': {
        relaxed: require('@/assets/guides/woman/exercises/21-smile-line-press/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/21-smile-line-press/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/21-smile-line-press/thumb.webp'),
      },
      '09-brow-lift': {
        relaxed: require('@/assets/guides/woman/exercises/09-brow-lift/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/09-brow-lift/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/09-brow-lift/thumb.webp'),
      },
      '22-forehead-press': {
        relaxed: require('@/assets/guides/woman/exercises/22-forehead-press/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/22-forehead-press/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/22-forehead-press/thumb.webp'),
      },
      '16-wide-eyes': {
        relaxed: require('@/assets/guides/woman/exercises/16-wide-eyes/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/16-wide-eyes/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/16-wide-eyes/thumb.webp'),
      },
      '17-lower-lid-lift': {
        relaxed: require('@/assets/guides/woman/exercises/17-lower-lid-lift/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/17-lower-lid-lift/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/17-lower-lid-lift/thumb.webp'),
      },
      '23-v-eyes': {
        relaxed: require('@/assets/guides/woman/exercises/23-v-eyes/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/23-v-eyes/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/23-v-eyes/thumb.webp'),
      },
      '10-eye-squeeze': {
        relaxed: require('@/assets/guides/woman/exercises/10-eye-squeeze/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/10-eye-squeeze/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/10-eye-squeeze/thumb.webp'),
      },
      '24-jaw-release': {
        relaxed: require('@/assets/guides/woman/exercises/24-jaw-release/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/24-jaw-release/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/24-jaw-release/thumb.webp'),
      },
      '25-jawline-sweep': {
        relaxed: require('@/assets/guides/woman/exercises/25-jawline-sweep/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/25-jawline-sweep/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/25-jawline-sweep/thumb.webp'),
      },
      '26-frown-release': {
        relaxed: require('@/assets/guides/woman/exercises/26-frown-release/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/26-frown-release/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/26-frown-release/thumb.webp'),
      },
      '27-temple-circles': {
        relaxed: require('@/assets/guides/woman/exercises/27-temple-circles/relaxed.webp'),
        exercise: require('@/assets/guides/woman/exercises/27-temple-circles/exercise.webp'),
        thumb: require('@/assets/guides/woman/exercises/27-temple-circles/thumb.webp'),
      },
    },
  },
} satisfies Partial<Record<GuideId, GuideImages>>;
